### ISSUE TITLE
Installer Woes

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#366] opened 2014-04-22 16:47 UTC
So, a coworker tried installing it (not Paul). He said it was a small inconvenience that the game didn't have a status bar or something indicating it was being installed.

Also, I tried installing it on a Windows 7 machine without .NET 4.5 installed. And totally got this error. Will try again after .NET is installed.

![stuff](https://cloud.githubusercontent.com/assets/2665239/2767890/5b76d78c-ca3d-11e3-87c3-513b2e4e8ae4.png)

**Comment by Quillwerth** [comment] 2014-04-22 17:26
You're sure that that error wasn't because you're on a dirty, evil Carlson
box?

**Comment by Quillwerth** [comment] 2014-04-22 17:27
Also, this is a partial duplicate of #364

**Comment by FourierTransformer** [comment] 2014-04-22 17:30
Perhaps maybe. But I've totally installed the game on a Carlson box in the
past using the old installer...

**Comment by bkern24** [comment] 2014-04-22 17:48
This used to work, possible computer error?

**Comment by lingqingmeng** [comment] 2014-04-22 19:44
I don't think the issue has to do with .NET. Has to do with the installer
doesn't have the ability to detect old installs and/or other files named
"setup.exe", hence the "unable to over-write". Try it again deleting all
conflicting filenames to confirm.

**Comment by AOEChamp** [comment] 2014-04-22 20:50
You ran the installer twice... The setup window in the background is being
overwritten by the extractor in the foreground, hence the error.

**Comment by bkern24** [comment] 2014-04-22 20:55
What a noob

**Closed as completed** 2014-04-24 15:11 UTC
