### ISSUE TITLE
Fix the damage of the Player Weapons

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#133] opened 2014-02-07 02:04 UTC
Fix the damage of the Player Weapons

**Comment by FourierTransformer** [comment] 2014-02-11 19:28
Update: I thought I was done, but then I plugged in a mouse and tried playing the game- holy crap, things just got easy (I went from not being able to beat round 3, to getting to round 5 - but then AOE mines got me). I'll keep balancing it in the meanwhile.

**Comment by FourierTransformer** [comment] 2014-02-12 06:31
So I think most of it is scaled decently. Sniper is still OP. I'll get to it after more play-testing soon enough.

**Comment by lingqingmeng** [comment] 2014-02-13 15:50
Who made mines AOE? Did you do anything else to modify mines? Just asking
since I was working on making Mines inflict damage even when mineDropper
enemy died, and also to make a limit (5) on the number of mines any given
mineDropper can drop.

**Comment by AOEChamp** [comment] 2014-02-15 23:03
Duplicate of #163

**Closed as completed by AOEChamp** 2014-02-15 23:03 UTC
