### ISSUE TITLE
Timing of KeyPress causes incorrect direction of player

### ISSUE THREAD

**Issue by bkern24** [4950/DirtyGame#180] opened 2014-02-15 20:50 UTC
Say I press "up" and then as I let go of the "up" key and press "right".... The player will be locked to "up" movement only until I release "right"

**Comment by AOEChamp** [comment] 2014-02-15 21:50
Hmm, either I failed in implementing the key queue, or Shak's extra keys messed it up. I'll take a look

**Comment by FourierTransformer** [comment] 2014-02-15 22:06
It was like that before I showed up. So, it wasn't me!

**Comment by AOEChamp** [comment] 2014-02-15 22:07
Someone want to pull my branch and see if it's gone? I can't reproduce it.

**Comment by bkern24** [comment] 2014-02-15 22:16
I pulled your branch, and I can reproduce it. It doesn't happen every time, and it doesn't have to be up and the right keys. Its any combination of two directions

**Comment by AOEChamp** [comment] 2014-02-15 22:55
Well, I'm not able to reproduce it with any key combinations. If the latest path doesn't fix it, then my guess is it's not related to movement so much as the InputManager. We don't get key events, instead we poll every frame. So it's possible that on laggy machines, some input gets skipped.

**Comment by AOEChamp** [comment] 2014-03-16 04:15
Pretty sure this is fixed. Closing unless it pops up again.

**Closed as completed by AOEChamp** 2014-03-16 04:15 UTC
Labels: bug
