### ISSUE TITLE
Balance other monsters

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#306] opened 2014-04-04 16:06 UTC
This is something that can be done if you have nothing else to work on. It is a low priority but I figured that at some point we should make the issue.

Balancing of the other monsters and weapons that we have created so we can push them back into the already balanced game of two weapons and three monsters. Look at the other monsters and weapons to get an idea of what the others should be.

**Comment by lingqingmeng** [comment] 2014-04-04 16:25
I'll work on it since Adeeb did my issue already.

**Comment by JaredPoetter** [comment] 2014-04-04 16:26
Ok I will assign it to you.

**Comment by lingqingmeng** [comment] 2014-04-08 00:15
I pushed to Conrad's latest branch origin/rangedAI (since its the farthest up). Close this once you confirmed you received the changes. @dawl

**Comment by JaredPoetter** [comment] 2014-04-15 03:02
Ling did you get to balancing the monsters? Or does this have to be reassigned?

**Comment by lingqingmeng** [comment] 2014-04-15 17:20
Reassign it. I pushed it to Conrads branch but I don't think he merged it.

**Comment by lingqingmeng** [comment] 2014-04-15 17:20
Shouldn't take too long, I have all the values with me.

**Comment by JaredPoetter** [comment] 2014-04-15 17:29
Could you just post the health and damage values for each enemy that you already did because we do not want to spend time trying to find the branch that you pushed those changes to. It would just save some time. Thanks.

**Comment by lingqingmeng** [comment] 2014-04-15 21:00
Yeah I'll get it tonight after work.

**Comment by lingqingmeng** [comment] 2014-04-16 02:12
patch notes
-GrenadeWeapon improved. Cooldown: 7->4. Base Damage: 20->17. Range
250->300.

Rationale: Compared to Archers, grenadiers have been a lot easier to combat.
We want both Monsters to be equally challenging, while still maintaining
unique differences amongst them. Grenades should be more frequent since
its very unlikely that you get hit by a Grenade compared to an arrow. Yes
I'm aware Arrows do less damage, but even if the damage ratio were more
equivalent... you would still take less total damage from grenades.

Range increase because when you run away from the Grenadier, they will try
and chase you but never fire unless within their specified range. This makes
the game look awkward and unprofessional.

-WallHugger weapon improved. Cooldown 2->1.8. Base Health 25->80

Rationale: They are slightly more predictable than archers because of the
way
their path is only on walls. Again, we want similar difficulty level for
each of the monsters. A slight reduction in cooldown will make facing them
more challenging. Since they are ranged immune, the improvement in base
health
is negligible, but should create more accurate PlayerScores.

**Comment by Duffman9205** [comment] 2014-04-17 03:56
I would also suggest the grenade fuse time be reduced from 2.0 to 0.5 to make them more dangerous. They're currently way too easy to avoid. (btw, the fuse time is set line 209 of WeaponSystem)

**Comment by Duffman9205** [comment] 2014-04-17 04:02
Also, the flame tower isn't really a threat in Arena, at least in the middle. I usually just run around it and kill it after everything else. Maybe make it's range higher?

**Comment by FourierTransformer** [comment] 2014-04-17 04:18
HOLY FLAMTHROWER THAT IS GOLD! Talk about taking anti-kiting to a new
extreme! Duffy, I freaking LOVE it! @AOEChamp the ball is now in your court.

**Comment by AOEChamp** [comment] 2014-04-17 04:21
All we need is a bigger and better flame texture

**Closed as completed** 2014-04-18 08:42 UTC
